region: ap-northeast-1
cluster: example-prod-laravel-fargate-app
service: example-prod-laravel-fargate-app
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://k-taiga-tfstate/example/prod/cicd/laravel-fargate-app_v1.0.0.tfstate
